### ISSUE TITLE
“任务”页的“报名的任务”和“发布的任务”没有显示任务状态

### ISSUE THREAD

**Issue by CarlSome** [SunBeachCat/AngryCat#12]
在“任务推荐”和“查找任务”页面的任务卡片不需要显示任务状态、只要显示任务类型。但是在“任务”页的“报名的任务”和“发布的任务”卡片上，还是需要显示当前任务状态的。
![image](https://user-images.githubusercontent.com/25930457/59818712-9acbdc00-9357-11e9-93c3-c073b2fe254f.png)

**Comment by gyakkun** [comment]
Done.
