### ISSUE TITLE
[低优先度]任务标题过长会导致详情页排版错误

### ISSUE THREAD

**Issue by CarlSome** [SunBeachCat/AngryCat#17]
如下图：
![image](https://user-images.githubusercontent.com/25930457/59912803-69cbd400-9449-11e9-80cc-eaf4d8d81402.png)
可以考虑限制标题长度，或者不要限制标题栏的高度

**Comment by Novemb11** [comment]
建议限制标题长度，标题过长影响美观

**Comment by CarlSome** [comment]
解决中

**Comment by CarlSome** [comment]
基本解决，但是当薪酬位数大于3位的时候，还是会出现问题
