### ISSUE TITLE
[低优先度-UX问题]发布任务的报错提示需要优化

### ISSUE THREAD

**Issue by CarlSome** [SunBeachCat/AngryCat#21]
如下图，目前的提示信息均比较“后端”，需要改为“人话”
![image](https://user-images.githubusercontent.com/25930457/59940102-69086180-948c-11e9-917b-aff0a58c5f66.png)

**Comment by gyakkun** [comment]
Done.
e79fadcb55c59996bf068dd7df50d7d898aa8e16
