### ISSUE TITLE
[中等优先度-UI问题]订单显示的状态不正确

### ISSUE THREAD

**Issue by CarlSome** [SunBeachCat/AngryCat#22]
订单存在的状态应为：进行中、候补中、已完成、已评价、已失效和已关闭。具体的状态机见链接：https://2019swsad.github.io/Dashboard/06-requirement-specification-4
部分状态可能后端还没有做，需要要求后端添加

**Comment by stwie2k** [comment]
需要后端返回信息更新

**Comment by CarlSome** [comment]
> 需要后端返回信息更新

与后端联系

**Comment by stwie2k** [comment]
已更改
