### ISSUE TITLE
参与者列表信息不正确

### ISSUE THREAD

**Issue by Novemb11** [SunBeachCat/AngryCat#35]
目前参与者列表是写死的

**Comment by stwie2k** [comment]
其实不是写死的，只是加了两个范例作为测试

**Comment by CarlSome** [comment]
另外{x}/{y}和{z}也还没有读取真实数据
![image](https://user-images.githubusercontent.com/25930457/59977234-6b3ffc80-9601-11e9-8561-f2b8484d5638.png)

**Comment by CarlSome** [comment]
候补人员的信息也写到“参与者”那里去了
![image](https://user-images.githubusercontent.com/25930457/59977295-223c7800-9602-11e9-879f-18b3f53f4e4b.png)

**Comment by CarlSome** [comment]
没有显示参与者的完成情况
![image](https://user-images.githubusercontent.com/25930457/59977435-74ca6400-9603-11e9-82ee-e986bd03c873.png)

**Comment by stwie2k** [comment]
完成情况不完整，还需要补齐状态，第一个列表可能需要后端更改接口，现在返回的是所有成员列表，最好是返回不带候选的列表
