### ISSUE TITLE
[中等优先度]item的用户名尚无法正常显示

### ISSUE THREAD

**Issue by Novemb11** [SunBeachCat/AngryCat#43]

**Comment by gyakkun** [comment]
[8297920](https://github.com/SunBeachCat/AngryCat/commit/829792052d066f2935f81651d2604f90ef2fbc0c) 解决过这个问题, 不过开销很大, revert了。

如果没有更好的办法再考虑这种实现。

**Comment by stwie2k** [comment]
还是不太理解，item的用户名不就是用户本人吗

**Comment by gyakkun** [comment]
> 还是不太理解，item的用户名不就是用户本人吗

是发布者

**Comment by Novemb11** [comment]
![image](https://user-images.githubusercontent.com/24909216/60072367-ced84000-974f-11e9-8c59-1d5aef04b51c.png)
箭头处缺少发布者用户名

**Comment by Novemb11** [comment]
如果开销很大就暂时不弄

**Comment by stwie2k** [comment]
> > 还是不太理解，item的用户名不就是用户本人吗
> 
> 是发布者

现在显示的发布的任务不是都应该是自己发布的吗，所以昵称也应该是自己才对吧

**Comment by Novemb11** [comment]
发布的任务是自己的，可是搜索任务、推荐任务、参与的任务有别人，这几个的处理逻辑是一样的，你这样做没解决根本问题

**Comment by stwie2k** [comment]
> 发布的任务是自己的，可是搜索任务、推荐任务、参与的任务有别人，这几个的处理逻辑是一样的，你这样做没解决根本问题
所以之前我才提了那个问题，发布任务应该不用加名称，搜索任务可以加一下，有一个比较好的办法就是后端接口里添加一个昵称信息，这样开销会小一点

**Comment by Novemb11** [comment]
后端提供接口的话开销不一定小，因为名称可以改，返回的名称要跟着改才行。或者有好的解决方案也可

**Comment by gyakkun** [comment]
Done.
d5d702975b5d7c4ac54c767c2c5dda8feea6290f
7147d7ccd1776f9fe034bccb5e62face73aff8b2
0e21438e2450b78759ace82270c94bf9577b7cf0
