### ISSUE TITLE
[中等优先度-UX问题]在取消报名资格后，没有即时更新参与者名单

### ISSUE THREAD

**Issue by CarlSome** [SunBeachCat/AngryCat#46]
如图：Carlsu已被取消资格，但是没有马上刷新页面，该用户依然停留在参与者列表中
![image](https://user-images.githubusercontent.com/25930457/60187526-4eedcb00-9860-11e9-8e0e-6b65aefc39e6.png)

**Comment by CarlSome** [comment]
转正同理

**Comment by CarlSome** [comment]
因人满导致转正失败后，没有相关的Toast提示

**Comment by stwie2k** [comment]
解决中

**Comment by stwie2k** [comment]
已解决
