### ISSUE TITLE
[中等优先度-UX问题]搜索任务中，仍然会显示已经停止报名的任务

### ISSUE THREAD

**Issue by CarlSome** [SunBeachCat/AngryCat#49]
如下图，理论上应该过滤掉已停止报名的任务
![image](https://user-images.githubusercontent.com/25930457/60229045-2d73fa00-98c7-11e9-8b84-ba568f0b78d8.png)

**Comment by gyakkun** [comment]
Done.
b6f0e1a4586d2a18bad2f3a4f4adb7617496279e
