### ISSUE TITLE
[高优先度]“用户昵称”的全局变量在保存后不能马上被获取

### ISSUE THREAD

**Issue by CarlSome** [SunBeachCat/AngryCat#9]
需要重新刷新整个程序才能够获取全局保存的“用户昵称”，

**Comment by stwie2k** [comment]
不是特别理解，我这边刷新后直接就可以获取昵称了

**Comment by CarlSome** [comment]
下图是在“我的钱包”中实时请求的用户昵称：
![image](https://user-images.githubusercontent.com/25930457/59744735-c8f0e380-92a5-11e9-963d-8f2440163995.png)
下图是在“我的”页面中显示的用户昵称：
![image](https://user-images.githubusercontent.com/25930457/59744814-f473ce00-92a5-11e9-99da-c2554d872879.png)
keyifaxian可以发现，“我的”页面中的用户昵称更新是滞后的。你可以通过更换账号登录来测试，可以发现“我的”页面显示的用户昵称是上一个用户的。或者你可以用手机测试，在初次登录时可以发现，“我的”页面的用户昵称为空

**Comment by CarlSome** [comment]
这个问题好像和全局变量有关。如：在app.js中更换登录账号并重新编译后，在发送请求时使用的cookie依然是上一个账号的cookie。需要再次编译才能获取新登录账号的cookie。看起来全局变量都会滞后

**Comment by stwie2k** [comment]
已更改
